"""initial schema — scan_runs, findings, chains, graph_snapshots, seed_meta

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-17

The schema is defined once in app.db.orm; this migration materialises it via
create_all so Alembic and the ORM never drift. Subsequent schema changes get
their own autogenerated revisions.
"""
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    from app.db.orm import Base
    Base.metadata.create_all(bind=op.get_bind())


def downgrade():
    from app.db.orm import Base
    Base.metadata.drop_all(bind=op.get_bind())
